export const licenseConst = [
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/animations@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/components",
    name: "@angular/cdk@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/common@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/compiler@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/core@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/forms@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/components",
    name: "@angular/material@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/platform-browser-dynamic@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/platform-browser@12.2.10",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "angular",
    name: "@angular/router@12.2.10",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/analytics@5.1.0",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/api-graphql@2.2.9",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/api-rest@2.0.20",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/api@4.0.20",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/auth@4.3.10",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/cache@4.0.22",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/core@4.3.2",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/datastore@3.4.8",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/geo@1.1.2",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/interactions@4.0.20",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/predictions@4.0.20",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/pubsub@4.1.12",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/storage@4.4.3",
    url: "",
  },
  {
    licenses: "Apache*",
    repository: "https://github.com/aws-amplify/amplify-js",
    name: "@aws-amplify/ui-angular@1.0.29",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    name: "@aws-amplify/ui-components@1.9.0",
    repository: "",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    name: "@aws-amplify/ui@2.0.3",
    repository: "",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "@aws-amplify/xr@3.0.20",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/crc32@1.2.2",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/ie11-detection@1.0.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/sha256-browser@1.2.2",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/sha256-js@1.2.2",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/supports-web-crypto@1.0.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-crypto-helpers",
    publisher: "AWS Crypto Tools Team",
    email: "aws-cryptools@amazon.com",
    url: "https://docs.aws.amazon.com/aws-crypto-tools/index.html?id=docs_gateway#lang/en_us",
    name: "@aws-crypto/util@1.2.2",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/abort-controller@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/chunked-blob-reader-native@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/chunked-blob-reader@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-cloudwatch-logs@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-cognito-identity@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-comprehend@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-firehose@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-kinesis@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-lex-runtime-service@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-location@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-personalize-events@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-pinpoint@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-polly@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-rekognition@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-s3@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-sso@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-sts@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-textract@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/client-translate@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/config-resolver@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-cognito-identity@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-env@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-imds@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-ini@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-process@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-sso@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/credential-provider-web-identity@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/eventstream-marshaller@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/eventstream-serde-browser@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/eventstream-serde-config-resolver@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/eventstream-serde-node@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/eventstream-serde-universal@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/fetch-http-handler@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/hash-blob-browser@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/hash-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/hash-stream-node@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/invalid-dependency@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/is-array-buffer@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/md5-js@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-apply-body-checksum@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-bucket-endpoint@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-content-length@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-expect-continue@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-header-default@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-host-header@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-location-constraint@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-logger@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-retry@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-sdk-s3@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-sdk-sts@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-serde@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-signing@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-ssec@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-stack@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/middleware-user-agent@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/node-config-provider@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/node-http-handler@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/property-provider@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/protocol-http@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/querystring-builder@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/querystring-parser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/s3-request-presigner@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/service-error-classification@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/shared-ini-file-loader@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/signature-v4@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/smithy-client@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/types@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/url-parser-native@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/url-parser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-arn-parser@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-base64-browser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-base64-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-body-length-browser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-body-length-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-buffer-from@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-create-request@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-credentials@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-format-url@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-hex-encoding@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-locate-window@3.37.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-uri-escape@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-user-agent-browser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-user-agent-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-utf8-browser@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-utf8-node@3.22.0",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/util-waiter@3.6.1",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws/aws-sdk-js-v3",
    publisher: "AWS SDK for JavaScript Team",
    url: "https://aws.amazon.com/javascript/",
    name: "@aws-sdk/xml-builder@3.6.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/capacitor",
    publisher: "Ionic Team",
    email: "hi@ionic.io",
    url: "https://ionic.io",
    name: "@capacitor/android@3.2.5",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/capacitor",
    publisher: "Ionic Team",
    email: "hi@ionic.io",
    url: "https://ionic.io",
    name: "@capacitor/core@3.2.5",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionic-native",
    publisher: "ionic",
    name: "@ionic-native/core@5.36.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionic-native",
    publisher: "ionic",
    name: "@ionic-native/in-app-browser@5.36.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionic-native",
    publisher: "ionic",
    name: "@ionic-native/keyboard@5.36.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionic",
    name: "@ionic/angular@5.8.4",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionic",
    publisher: "Ionic Team",
    name: "@ionic/core@5.8.4",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ngx-translate/core",
    publisher: "Olivier Combe",
    name: "@ngx-translate/core@13.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ngx-translate/http-loader",
    publisher: "Olivier Combe",
    name: "@ngx-translate/http-loader@6.0.0",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/commons",
    name: "@sinonjs/commons@1.8.3",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/formatio",
    publisher: "Christian Johansen",
    name: "@sinonjs/formatio@3.2.2",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/samsam",
    publisher: "Christian Johansen",
    name: "@sinonjs/samsam@3.3.3",
    url: "",
  },
  {
    licenses: "(Unlicense OR Apache-2.0)",
    repository: "https://github.com/inexorabletash/text-encoding",
    publisher: "Joshua Bell",
    email: "inexorabletash@gmail.com",
    name: "@sinonjs/text-encoding@0.7.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/stencil",
    publisher: "Ionic Team",
    name: "@stencil/core@2.9.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    name: "@types/cookie@0.3.3",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/DefinitelyTyped/DefinitelyTyped",
    publisher: "Microsoft Open Technologies Inc",
    email: "http://msopentech.com",
    name: "@types/cordova@0.0.34",
    url: "",
  },
  {
    licenses: "Custom: https://github.com/aws-amplify/amplify-js",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    email: "aws@amazon.com",
    url: "http://aws.amazon.com",
    noticeFile:
      "E:\\Projects\\aws\\amplifyIonic\\ShareTodo\\node_modules\\amazon-cognito-identity-js\\NOTICE.txt",
    name: "amazon-cognito-identity-js@5.2.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chalk/ansi-regex",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "ansi-regex@4.1.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chalk/ansi-styles",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "ansi-styles@3.2.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/studio-b12/array-from",
    name: "array-from@2.1.1",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/aws-amplify/amplify-js",
    publisher: "Amazon Web Services",
    name: "aws-amplify@4.3.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/axios/axios",
    publisher: "Matt Zabriskie",
    name: "axios@0.21.4",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/beatgammit/base64-js",
    publisher: "T. Jameson Little",
    email: "t.jameson.little@gmail.com",
    name: "base64-js@1.5.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/lancedikson/bowser",
    publisher: "Dustin Diaz",
    email: "dustin@dustindiaz.com",
    url: "http://dustindiaz.com",
    name: "bowser@2.11.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/buffer-alloc-unsafe",
    name: "buffer-alloc-unsafe@1.1.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/buffer-alloc",
    name: "buffer-alloc@1.2.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/buffer-fill",
    name: "buffer-fill@1.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/buffer-from",
    name: "buffer-from@1.1.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/feross/buffer",
    publisher: "Feross Aboukhadijeh",
    email: "feross@feross.org",
    url: "https://feross.org",
    name: "buffer@5.7.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/camelcase-keys",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "camelcase-keys@6.2.2",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/camelcase",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "camelcase@5.3.1",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/yargs/cliui",
    publisher: "Ben Coe",
    email: "ben@npmjs.com",
    name: "cliui@5.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/Qix-/color-convert",
    publisher: "Heather Arthur",
    email: "fayearthur@gmail.com",
    name: "color-convert@1.9.3",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/dfcreative/color-name",
    publisher: "DY",
    email: "dfcreative@gmail.com",
    name: "color-name@1.1.3",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/jshttp/cookie",
    publisher: "Roman Shtylman",
    email: "shtylman@gmail.com",
    name: "cookie@0.4.1",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/apache/cordova-plugin-inappbrowser",
    publisher: "Apache Software Foundation",
    noticeFile:
      "E:\\Projects\\aws\\amplifyIonic\\ShareTodo\\node_modules\\cordova-plugin-inappbrowser\\NOTICE",
    name: "cordova-plugin-inappbrowser@5.0.0",
    url: "",
  },
  {
    licenses: "MIT*",
    repository: "https://github.com/ionic-team/cordova-plugin-ionic-keyboard",
    publisher: "Apache Software Foundation",
    name: "cordova-plugin-ionic-keyboard@2.2.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/brix/crypto-js",
    publisher: "Evan Vosberg",
    url: "http://github.com/evanvosberg",
    name: "crypto-js@4.1.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/decamelize",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "decamelize@1.2.0",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/kpdecker/jsdiff",
    name: "diff@3.5.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/tcort/dijkstrajs",
    name: "dijkstrajs@1.0.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/mathiasbynens/emoji-regex",
    publisher: "Mathias Bynens",
    url: "https://mathiasbynens.be/",
    name: "emoji-regex@7.0.3",
  },
  {
    licenses: "BSD-2-Clause",
    repository: "https://github.com/fb55/entities",
    publisher: "Felix Boehm",
    email: "me@feedic.com",
    name: "entities@2.2.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/Gozala/events",
    publisher: "Irakli Gozalishvili",
    email: "rfobic@gmail.com",
    url: "http://jeditoolkit.com",
    name: "events@3.3.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/fast-base64-decode",
    name: "fast-base64-decode@1.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/NaturalIntelligence/fast-xml-parser",
    publisher: "Amit Gupta",
    url: "https://amitkumargupta.work/",
    name: "fast-xml-parser@3.19.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/find-up",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "find-up@3.0.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/follow-redirects/follow-redirects",
    publisher: "Ruben Verborgh",
    email: "ruben@verborgh.org",
    url: "https://ruben.verborgh.org/",
    name: "follow-redirects@1.14.4",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/stefanpenner/get-caller-file",
    publisher: "Stefan Penner",
    name: "get-caller-file@2.0.5",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/graphql/graphql-js",
    name: "graphql@14.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/has-flag",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "has-flag@3.0.0",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/jakearchibald/idb",
    publisher: "Jake Archibald",
    name: "idb@5.0.6",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/feross/ieee754",
    publisher: "Feross Aboukhadijeh",
    email: "feross@feross.org",
    url: "https://feross.org",
    name: "ieee754@1.2.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/immerjs/immer",
    publisher: "Michel Weststrate",
    name: "immer@9.0.6",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ionic-team/ionicons",
    publisher: "Ben Sperry",
    url: "https://twitter.com/benjsperry",
    name: "ionicons@5.5.3",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/is-fullwidth-code-point",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "is-fullwidth-code-point@2.0.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/juliangruber/isarray",
    publisher: "Julian Gruber",
    email: "mail@juliangruber.com",
    url: "http://juliangruber.com",
    name: "isarray@2.0.5",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/developit/unfetch",
    name: "isomorphic-unfetch@3.1.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/leebyron/iterall",
    publisher: "Lee Byron",
    email: "lee@leebyron.com",
    url: "http://leebyron.com/",
    name: "iterall@1.3.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/js-cookie/js-cookie",
    publisher: "Klaus Hartl",
    name: "js-cookie@2.2.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angus-c/just",
    publisher: "Angus Croll",
    name: "just-extend@4.2.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/locate-path",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "locate-path@3.0.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/lodash/lodash",
    publisher: "John-David Dalton",
    email: "john.david.dalton@gmail.com",
    name: "lodash@4.17.21",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/lolex",
    publisher: "Christian Johansen",
    name: "lolex@5.1.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/map-obj",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "https://sindresorhus.com",
    name: "map-obj@4.3.0",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/nise",
    name: "nise@1.5.3",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/bitinn/node-fetch",
    publisher: "David Frank",
    name: "node-fetch@2.6.5",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/p-limit",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "p-limit@2.3.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/p-locate",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "p-locate@3.0.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/p-try",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "p-try@2.2.0",
  },
  {
    licenses: "EPL-1.0",
    repository: "https://github.com/eclipse/paho.mqtt.javascript",
    publisher: "Andrew Banks",
    url: "Initial Author",
    name: "paho-mqtt@1.1.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/inikulin/parse5",
    publisher: "Ivan Nikulin",
    email: "ifaaan@gmail.com",
    url: "https://github.com/inikulin",
    name: "parse5@5.1.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/path-exists",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "path-exists@3.0.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/pillarjs/path-to-regexp",
    name: "path-to-regexp@1.8.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/lukeapage/pngjs2",
    name: "pngjs@3.4.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/bestiejs/punycode.js",
    publisher: "Mathias Bynens",
    url: "https://mathiasbynens.be/",
    name: "punycode@1.3.2",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/soldair/node-qrcode",
    publisher: "Ryan Day",
    email: "soldair@gmail.com",
    name: "qrcode@1.4.4",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/Gozala/querystring",
    publisher: "Irakli Gozalishvili",
    email: "rfobic@gmail.com",
    name: "querystring@0.2.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/quick-lru",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "quick-lru@4.0.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/LinusU/react-native-get-random-values",
    name: "react-native-get-random-values@1.7.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/troygoode/node-require-directory",
    publisher: "Troy Goode",
    email: "troygoode@gmail.com",
    url: "http://github.com/troygoode/",
    name: "require-directory@2.1.1",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/yargs/require-main-filename",
    publisher: "Ben Coe",
    email: "ben@npmjs.com",
    name: "require-main-filename@2.0.0",
    url: "",
  },
  {
    licenses: "Apache-2.0",
    repository: "https://github.com/reactivex/rxjs",
    publisher: "Ben Lesh",
    email: "ben@benlesh.com",
    name: "rxjs@6.5.5",
    url: "",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/yargs/set-blocking",
    publisher: "Ben Coe",
    email: "ben@npmjs.com",
    name: "set-blocking@2.0.0",
    url: "",
  },
  {
    licenses: "BSD-3-Clause",
    repository: "https://github.com/sinonjs/sinon",
    publisher: "Christian Johansen",
    name: "sinon@7.5.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/sindresorhus/string-width",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "string-width@3.1.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chalk/strip-ansi",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "strip-ansi@5.2.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chalk/supports-color",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "supports-color@5.5.0",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/Sebmaster/tr46.js",
    publisher: "Sebastian Mayr",
    email: "npm@smayr.name",
    name: "tr46@0.0.3",
    url: "",
  },
  {
    licenses: "0BSD",
    repository: "https://github.com/Microsoft/tslib",
    publisher: "Microsoft Corp.",
    name: "tslib@2.3.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chaijs/type-detect",
    publisher: "Jake Luer",
    email: "jake@alogicalparadox.com",
    url: "http://alogicalparadox.com",
    name: "type-detect@4.0.8",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/ulid/javascript",
    publisher: "Alizain Feerasta",
    name: "ulid@2.3.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/developit/unfetch",
    name: "unfetch@4.2.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/reactivestack/cookies",
    publisher: "Benoit Tremblay",
    email: "benoit@reactivestack.com",
    name: "universal-cookie@4.0.4",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/defunctzombie/node-url",
    name: "url@0.11.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/uuidjs/uuid",
    name: "uuid@8.3.2",
    url: "",
  },
  {
    licenses: "BSD-2-Clause",
    repository: "https://github.com/jsdom/webidl-conversions",
    publisher: "Domenic Denicola",
    email: "d@domenic.me",
    url: "https://domenic.me/",
    name: "webidl-conversions@3.0.1",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/jsdom/whatwg-url",
    publisher: "Sebastian Mayr",
    email: "github@smayr.name",
    name: "whatwg-url@5.0.0",
    url: "",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/nexdrew/which-module",
    publisher: "nexdrew",
    name: "which-module@2.0.0",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/chalk/wrap-ansi",
    publisher: "Sindre Sorhus",
    email: "sindresorhus@gmail.com",
    url: "sindresorhus.com",
    name: "wrap-ansi@5.1.0",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/yargs/y18n",
    publisher: "Ben Coe",
    email: "ben@npmjs.com",
    name: "y18n@4.0.3",
    url: "",
  },
  {
    licenses: "ISC",
    repository: "https://github.com/yargs/yargs-parser",
    publisher: "Ben Coe",
    email: "ben@npmjs.com",
    name: "yargs-parser@13.1.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/yargs/yargs",
    name: "yargs@13.3.2",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/apollographql/apollo-link",
    publisher: "Evans Hauser",
    email: "evanshauser@gmail.com",
    name: "zen-observable-ts@0.8.19",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/zenparsing/zen-observable",
    name: "zen-observable@0.8.15",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/zenparsing/zen-push",
    name: "zen-push@0.2.1",
    url: "",
  },
  {
    licenses: "MIT",
    repository: "https://github.com/angular/angular",
    publisher: "Brian Ford",
    name: "zone.js@0.11.4",
    url: "",
  },
  {
    licenses: "Designed by Freepik and distributed by Flaticon",
    repository: "",
    publisher: "",
    name: "App icon",
    url: "https://www.flaticon.com/authors/freepik",
  },
] as const;
